### ISSUE TITLE
Avoid predicates on the left edge of lexer rules

### ISSUE THREAD

**Issue by sharwell** [davidbrownell/Common_SimpleSchemaGenerator#1]
https://github.com/davidbrownell/Common_SimpleSchemaGenerator/blob/889f4cc84c956af1e4a3c5491a75dd44d9e3f136/src/SimpleSchemaGenerator/Schema/Grammar/SimpleSchema.g4#L29-L30

Lexer predicates disable DFA edge caching, so you want to minimize the number of times the predicate is seen during lexing. The easiest way to do this is move the predicate from the beginning of the rule to the end of the rule, so it's only evaluated if the input sequence requires it.

**Comment by davidbrownell** [comment]
Fixed - pending checkin.
