### ISSUE TITLE
Consider using more robust string lexer rules

### ISSUE THREAD

**Issue by sharwell** [davidbrownell/Common_SimpleSchemaGenerator#2]
Currently strings are evaluated using these rules:

https://github.com/davidbrownell/Common_SimpleSchemaGenerator/blob/889f4cc84c956af1e4a3c5491a75dd44d9e3f136/src/SimpleSchemaGenerator/Schema/Grammar/SimpleSchema.g4#L65-L69

The following shows a more robust way of evaluating character sequences with a start and end delimiter, such that error recovery and reporting is more usable. Note that this link shows the lexer rules for _one type_ of string. Other examples appear in the same lexer for other types of strings. You'll want to adapt the concepts to the specific form of string used by your grammar.

https://github.com/tunnelvisionlabs/antlr4-grammar-postgresql/blob/4c4d8e6a8f3057b319365ec947e6e76cc5a22e14/src/com/tunnelvisionlabs/postgresql/PostgreSqlLexer.g4#L609-L636

**Comment by davidbrownell** [comment]
This could be a limitation around my understanding of ANTLR grammars, but when I follow the code you provided and change the string processing to:

```doubleQuotedIdentifier__:                   doubleQuotedUnterminatedIdentifier__ '"';
doubleQuotedUnterminatedIdentifier__:       '"' ('\\"' | '\\\\' | ~'"')*?;

singleQuotedIdentifier__:                   singleQuotedUnterminatedIdentifier__ '\'';
singleQuotedUnterminatedIdentifier__:       '\'' ('\\\'' | '\\\\' | ~'\'')*?;

tripleDoubleQuotedIdentifier__:             tripleDoubleQuotedUnterminatedIdentifier__ '"""';
tripleDoubleQuotedUnterminatedIdentifier__: '"""' .*?;

tripleSingleQuotedIdentifier__:             tripleSingleQuotedUnterminatedIdentifier__ '\'\'\'';
tripleSingleQuotedUnterminatedIdentifier__: '\'\'\'' .*?;

string:                                     doubleQuotedIdentifier__ | singleQuotedIdentifier__;
enhancedString:                             string | tripleDoubleQuotedIdentifier__ | tripleSingleQuotedIdentifier__;
```

I run into problems because all of the whitespace is stripped from the strings - this is likely due to the tokenization rule on line 32:

`HORIZONTAL_WHITESPACE:                      [ \t]+ -> skip;`

Is there a way for a lexer rule to temporarily disable a tokenizing rule?

**Comment by sharwell** [comment]
```
doubleQuotedUnterminatedIdentifier__
```

This was changed to a parser rule. The example still uses lexer rules for the strings, but instead of one possible token for each string you have four possible tokens (1 valid and 3 error).

**Comment by sharwell** [comment]
The parser rule might look like this at the end:

```
string
  : // Normal strings
    DOUBLE_QUOTE_STRING
  | SINGLE_QUOTE_STRING
  | TRIPLE_DOUBLE_QUOTE_STRING
  | TRIPLE_SINGLE_QUOTE_STRING

  // Unterminated strings
  | UNTERMINATED_DOUBLE_QUOTE_STRING
  | UNTERMINATED_SINGLE_QUOTE_STRING
  | UNTERMINATED_TRIPLE_DOUBLE_QUOTE_STRING
  | UNTERMINATED_TRIPLE_SINGLE_QUOTE_STRING

  // Strings with invalid content
  | INVALID_DOUBLE_QUOTE_STRING
  | INVALID_SINGLE_QUOTE_STRING
  | INVALID_TRIPLE_DOUBLE_QUOTE_STRING
  | INVALID_TRIPLE_SINGLE_QUOTE_STRING

  // Unterminated strings with invalid content
  | INVALID_UNTERMINATED_DOUBLE_QUOTE_STRING
  | INVALID_UNTERMINATED_SINGLE_QUOTE_STRING
  | INVALID_UNTERMINATED_TRIPLE_DOUBLE_QUOTE_STRING
  | INVALID_UNTERMINATED_TRIPLE_SINGLE_QUOTE_STRING
  ;
```

**Comment by davidbrownell** [comment]
Fixed - pending checkin
